version: '3.5'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins-home:/var/jenkins_home"

volumes:
  jenkins-home:
    external: true
